blank_issues_enabled: false
contact_links:
  - name: ğŸ™‹ğŸ» ë¬¸ì˜ëŠ” ìŠ¬ë™ìœ¼ë¡œ
    url: https://theskala.slack.com/archives/C08SX9K42G5
    about: ì´ìŠˆê°€ ì•„ë‹ˆë¼ ì§ˆë¬¸ì´ë¼ë©´ ìŠ¬ë™ìœ¼ë¡œ ë¬¸ì˜í•´ì£¼ì„¸ìš”.
